In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import ensemble
from sklearn.model_selection import cross_val_score
from sklearn.decomposition import PCA
%matplotlib inline

In [2]:
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1, nrows=50000
)

y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
y2015.describe()

id     member_id     loan_amnt   funded_amnt  \
count  5.000000e+04  5.000000e+04  50000.000000  50000.000000   
mean   6.670962e+07  7.144267e+07  15019.333500  15019.333500   
std    1.942347e+06  2.243390e+06   8676.180969   8676.180969   
min    6.702500e+04  2.484710e+05   1000.000000   1000.000000   
25%    6.594684e+07  7.064157e+07   8000.000000   8000.000000   
50%    6.654286e+07  7.126861e+07  14000.000000  14000.000000   
75%    6.744762e+07  7.224896e+07  20000.000000  20000.000000   
max    6.861706e+07  7.354484e+07  35000.000000  35000.000000   

       funded_amnt_inv      int_rate   installment    annual_inc  \
count      50000.00000  50000.000000  50000.000000  5.000000e+04   
mean       15011.79400     12.236739    434.134945  7.919482e+04   
std         8671.20408      4.190234    247.503896  1.013218e+05   
min          950.00000      5.320000     30.540000  0.000000e+00   
25%         8000.00000      9.170000    255.040000  4.800000e+04   
50%        13900.00000     11.990000    378.150000  6.600000e+04   
75%        20000.00000     14.480000    573.810000  9.500000e+04   
max        35000.00000     28.990000   1354.660000  9.000000e+06   

                dti   delinq_2yrs             ...              \
count  50000.000000  50000.000000             ...               
mean      19.540321      0.345620             ...               
std       45.737896      0.910441             ...               
min        0.000000      0.000000             ...               
25%       12.680000      0.000000             ...               
50%       18.820000      0.000000             ...               
75%       25.620000      0.000000             ...               
max     9999.000000     15.000000             ...               

       num_tl_90g_dpd_24m  num_tl_op_past_12m  pct_tl_nvr_dlq  \
count        50000.000000        50000.000000    50000.000000   
mean             0.093180            2.245820       93.814492   
std              0.507644            1.906606        9.038545   
min              0.000000            0.000000       12.500000   
25%              0.000000            1.000000       90.900000   
50%              0.000000            2.000000       97.300000   
75%              0.000000            3.000000      100.000000   
max             14.000000           30.000000      100.000000   

       percent_bc_gt_75  pub_rec_bankruptcies     tax_liens  tot_hi_cred_lim  \
count      49504.000000          50000.000000  50000.000000     5.000000e+04   
mean          45.537807              0.139320      0.068040     1.773950e+05   
std           36.311435              0.393844      0.455384     1.772051e+05   
min            0.000000              0.000000      0.000000     2.500000e+03   
25%           11.100000              0.000000      0.000000     5.270000e+04   
50%           42.900000              0.000000      0.000000     1.152950e+05   
75%           75.000000              0.000000      0.000000     2.554300e+05   
max          100.000000              8.000000     25.000000     4.037303e+06   

       total_bal_ex_mort  total_bc_limit  total_il_high_credit_limit  
count       50000.000000    50000.000000                50000.000000  
mean        53376.550720    22657.988700                45269.696840  
std         48872.446963    22498.091256                44708.412285  
min             0.000000        0.000000                    0.000000  
25%         23197.000000     8000.000000                16663.750000  
50%         40633.500000    15600.000000                34672.000000  
75%         67700.000000    29500.000000                60522.000000  
max        882172.000000   307500.000000               975560.000000  

[8 rows x 87 columns]

In [4]:
rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=5)

c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in ve

array([0.98190362, 0.98140186, 0.98160184, 0.9803    , 0.94637855])

In [5]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in ve

array([0.98260696, 0.980008  , 0.98040784, 0.98120376, 0.9810038 ,
       0.9812    , 0.98019604, 0.9809962 , 0.98279656, 0.98018018])

In [6]:
pca = PCA(n_components=10) #10-fold cross validation
pca.fit(X)
X_pca = pca.transform(X)
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_pca, Y, cv=10)

c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in ve

array([0.93022791, 0.93842463, 0.93622551, 0.93921216, 0.94281144,
       0.9402    , 0.94138828, 0.9379876 , 0.93678736, 0.93873874])

In [12]:
X.columns[:25]

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'int_rate', 'installment', 'annual_inc', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'total_acc',
       'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt'],
      dtype='object')

In [8]:
columns = ['out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int','last_pymnt_amnt']

X_trim = X.drop(columns=columns)

rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_trim, Y, cv=10)

c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\ben\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in ve

array([0.94942023, 0.95561775, 0.95221911, 0.95480904, 0.95640872,
       0.959     , 0.95839168, 0.95439088, 0.94478896, 0.95575576])

Yes, the accuracy rate of more than 90% (based on the data above) can be achieved as long as those variables are not included in the data set.